# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in rakefile.rb, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{rocksalt}
  s.version = "0.1.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Derick Bailey", "Josh Flanagan"]
  s.date = %q{2010-02-11}
  s.default_executable = %q{rocksalt}
  s.description = %q{Manage your .NET reference assemblies by downloading gem packages, and coping the project assembly to your solution library.}
  s.email = %q{derickbailey@gmail.com}
  s.executables = ["rocksalt"]
  s.extra_rdoc_files = [
    "LICENSE.txt"
  ]
  s.files = [
    "LICENSE.txt",
     "VERSION",
     "bin/rocksalt",
     "lib/commandline.rb",
     "lib/dropspreader.rb",
     "lib/rocksalt.rb",
     "rakefile.rb",
     "specs/manifest_parsing_spec.rb"
  ]
  s.homepage = %q{http://github.com/derickbailey/rocksalt}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.5}
  s.summary = %q{A .NET Assembly Manager Using RubyGems}

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<rake>, [">= 0.8.7"])
      s.add_development_dependency(%q<rspec>, [">= 1.2.8"])
      s.add_development_dependency(%q<jeweler>, [">= 1.2.1"])
      s.add_development_dependency(%q<derickbailey-notamock>, [">= 0.0.1"])
      s.add_development_dependency(%q<jekyll>, [">= 0.5.4"])
    else
      s.add_dependency(%q<rake>, [">= 0.8.7"])
      s.add_dependency(%q<rspec>, [">= 1.2.8"])
      s.add_dependency(%q<jeweler>, [">= 1.2.1"])
      s.add_dependency(%q<derickbailey-notamock>, [">= 0.0.1"])
      s.add_dependency(%q<jekyll>, [">= 0.5.4"])
    end
  else
    s.add_dependency(%q<rake>, [">= 0.8.7"])
    s.add_dependency(%q<rspec>, [">= 1.2.8"])
    s.add_dependency(%q<jeweler>, [">= 1.2.1"])
    s.add_dependency(%q<derickbailey-notamock>, [">= 0.0.1"])
    s.add_dependency(%q<jekyll>, [">= 0.5.4"])
  end
end

